script: "bundle exec rake ci"
rvm:
  - ruby-head
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-head
  - rbx-19mode
  - rbx-18mode
matrix:
  allow_failures:
    - rvm: jruby-head

# - jruby-18mode
# - jruby-head
