script: "bundle exec rake ci"
rvm:
  - ruby-head
  - 2.1.1
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-head
  - jruby-19mode
  - rbx-19mode
env:
  - RSPEC_VERSION=master
  - RSPEC_VERSION=2.99.0.beta2
  - RSPEC_VERSION=2.14
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode
