language: ruby

rvm:
  - 1.8.7
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-head
  - jruby-19mode
  - rbx-19mode

env:
  - RSPEC_VERSION=master
  - RSPEC_VERSION='~> 3.0.0'
  - RSPEC_VERSION='~> 2.99.0'
  - RSPEC_VERSION='~> 2.14.0'

bundler_args: "--retry=3 --jobs=3"

script: "bundle exec rake ci --trace"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode
