script: "bundle exec rake ci"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-18mode   # some cucumber "rake spec" timeouts (just slowness I think)
